### ISSUE TITLE
Bluehost 2012 had their boxes exposed online

### ISSUE THREAD

**Issue by princezuda** [disclose/diodata#8]
Bluehost 2012 had their boxes completely accessible and threatened to sue if my company reported on it. If memory serves, they had bin/etc usr/bin exposed and access to the shells of boxes they hosted in Google Cache...... yeah.

**Comment by attritionorg** [comment]
What year was that? And this was after you warned them of the security issue right?

**Comment by princezuda** [comment]
It was the 2011-2012 era when almost all webhosts were having this issue. I called them and I was told they would sue me. I had tried repeatedly to get hold of them, it was impossible to find anyone who cared.

**Comment by princezuda** [comment]
When I got someone yeah I was told they would sue me.
